//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AİRHOKEY.Properties
{


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
	{

		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

		public static Settings Default
		{
			get
			{
				return defaultInstance;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Green")]
		public global::System.Drawing.Color Color_picPlayer1
		{
			get
			{
				return ((global::System.Drawing.Color)(this["Color_picPlayer1"]));
			}
			set
			{
				this["Color_picPlayer1"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Red")]
		public global::System.Drawing.Color Color_picPlayer2
		{
			get
			{
				return ((global::System.Drawing.Color)(this["Color_picPlayer2"]));
			}
			set
			{
				this["Color_picPlayer2"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("White")]
		public global::System.Drawing.Color Color_picTop
		{
			get
			{
				return ((global::System.Drawing.Color)(this["Color_picTop"]));
			}
			set
			{
				this["Color_picTop"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Turquoise")]
		public global::System.Drawing.Color Color_Form
		{
			get
			{
				return ((global::System.Drawing.Color)(this["Color_Form"]));
			}
			set
			{
				this["Color_Form"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("2")]
		public int Player1Hizi
		{
			get
			{
				return ((int)(this["Player1Hizi"]));
			}
			set
			{
				this["Player1Hizi"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("2")]
		public int Player2Hizi
		{
			get
			{
				return ((int)(this["Player2Hizi"]));
			}
			set
			{
				this["Player2Hizi"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("6")]
		public int TopHizi
		{
			get
			{
				return ((int)(this["TopHizi"]));
			}
			set
			{
				this["TopHizi"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("1")]
		public int TopTimerHizi
		{
			get
			{
				return ((int)(this["TopTimerHizi"]));
			}
			set
			{
				this["TopTimerHizi"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("1")]
		public int Player2TimerHizi
		{
			get
			{
				return ((int)(this["Player2TimerHizi"]));
			}
			set
			{
				this["Player2TimerHizi"] = value;
			}
		}
	}
}
